# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3bbd9cb1df80773e5e282c4ef610fb54d316b2b113ed3567b11bbcad3cb3e4278936f866256b209269b56cca3daae0b0c50f568e774b2c083caf000b064a9812

test:
  secret_key_base: a1c66af1cc520840e2af5567f3776612bfa55bb2a9fe3e4ba6269848c99eeaf64c5f1d98543c8cf3797ba1ea9fae7361c70a9d0fd5e9601299144bd749e3a90c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
